export const appMenuItems = [
  {
    id: 1,
    name: "Dashboard",
    link: "/dashboard",
    Icon: "/images/dashboard.png",
    IconActive: "/images/dashboardActive.png",
  },
  {
    id: 2,
    name: "Feeds",
    link: "/feeds",
    Icon: "/images/feeds.png",
    IconActive: "/images/feedsActive.png",
  },
  {
    id: 3,
    name: "Proposals",
    link: "/proposals",
    Icon: "/images/proposals.png",
    IconActive: "/images/proposalsActive.png",
  },
  {
    id: 4,
    name: "My Jobs",
    link: "/my-jobs",
    Icon: "/images/jobs.png",
    IconActive: "/images/jobsActive.png",
  },
  {
    id: 5,
    name: "My Contracts",
    link: "/contracts",
    Icon: "/images/contracts.png",
    IconActive: "/images/contractsActive.png",
  },
  {
    id: 6,
    name: "Chats",
    link: "/chats",
    Icon: "/images/chats.png",
    IconActive: "/images/chatsActive.png",
  },
  {
    id: 7,
    name: "Payment Methods",
    link: "/payment",
    Icon: "/images/payment.png",
    IconActive: "/images/paymentActive.png",
  },
  {
    id: 8,
    name: "Payment",
    link: "/transaction",
    Icon: "/images/payment.png",
    IconActive: "/images/paymentActive.png",
  },
  {
    id: 9,
    name: "Profile",
    link: "/profile",
    Icon: "/images/profile.png",
    IconActive: "/images/profileActive.png",
  },
  {
    id: 10,
    name: "Notifications",
    link: "/notifications",
    Icon: "/images/notifications.png",
    IconActive: "/images/notificationsActive.png",
  },
  {
    id: 11,
    name: "Account Settings",
    link: "/settings",
    Icon: "/images/settings.png",
    IconActive: "/images/settingsActive.png",
  },
  {
    id: 12,
    name: "Help & Support",
    link: "/help-support",
    Icon: "/images/support.png",
    IconActive: "/images/supportActive.png",
  },
  {
    id: 13,
    name: "Jobs",
    link: "/publish",
    Icon: "/images/payment.png",
    IconActive: "/images/paymentActive.png",
},
  {
    id: 14,
    name: "Logout",
    link: "/logout",
    Icon: "/images/logout.png",
    IconActive: "/images/logoutActive.png",
  },
];
export const ClientMenu = [
  {
    id: 1,
    name: "Dashboard",
    link: "/client-dashboard",
    Icon: "/images/dashboard.png",
    IconActive: "/images/dashboardActive.png",
},
{
  id: 2,
  name: "Payment",
  link: "/payment-client",
  Icon: "/images/payment.png",
  IconActive: "/images/paymentActive.png",
},
  ]
export const TALENT_ROLE = 1;
// export const routesConfig = {
//   "/": {
//     path: "/",
//     redirect: "/",
//     protected: false,
//     access: [TALENT_ROLE],
//   },
//   "/dashboard": {
//     path: "/dashboard",
//     redirect: "/dashboard",
//     protected: true,
//     access: [TALENT_ROLE],
//   },
//   "/my-jobs": {
//     path: "/my-jobs",
//     redirect: "/",
//     protected: true,
//     access: [TALENT_ROLE],
//   },
//   "/chats": {
//     path: "/chats",
//     redirect: "/",
//     protected: true,
//     access: [TALENT_ROLE],
//   },
//   "/chats/[id]": {
//     path: "/chats/[id]",
//     redirect: "/",
//     protected: true,
//     access: [TALENT_ROLE],
//   },
//   "/payment": {
//     path: "/payment",
//     redirect: "/",
//     protected: true,
//     access: [TALENT_ROLE],
//   },
//   "/payment/success": {
//     path: "/method/success",
//     redirect: "/",
//     protected: true,
//     access: [TALENT_ROLE],
//   },
//   "/profile": {
//     path: "/profile",
//     redirect: "/",
//     protected: true,
//     access: [TALENT_ROLE],
//   },
//   "/notifications": {
//     path: "/notifications",
//     redirect: "/",
//     protected: true,
//     access: [TALENT_ROLE],
//   },
//   "/settings": {
//     path: "/settings",
//     redirect: "/",
//     protected: true,
//     access: [TALENT_ROLE],
//   },
//   "/help-support": {
//     path: "/help-support",
//     redirect: "/",
//     protected: true,
//     access: [TALENT_ROLE],
//   },
//   "/logout": {
//     path: "/logout",
//     redirect: "/",
//     protected: true,
//     access: [TALENT_ROLE],
//   },
// };