import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import MainPage from '../../src/components/common/mainpage/index';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Torsin Talent App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/torsinLogo.png" />
            </Head>
            <main>
                <MainPage />
            </main>
        </div>
    )
} 
