import React, { useEffect, useState } from 'react'
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import MainPage from '../src/components/common/mainpage/index';
import Layout from "../src/components/common/MainHeaderFooterLayout";
import Dashboard from "../src/components/dashboard/Dashboard";
import * as firebase from 'firebase/app';
import { onMessage, getMessaging } from 'firebase/messaging';
import { LazyLoader } from '../src/components/common/LazyLoader';
import { useRouter } from 'next/router';

// const firebaseConfig = {
//   apiKey: "AIzaSyAE0443y1oY7EgAiJJ-EHhiOhIHFhYipI0",
//   authDomain: "torsin-6084e.firebaseapp.com",
//   databaseURL: "https://torsin-6084e-default-rtdb.firebaseio.com",
//   projectId: "torsin-6084e",
//   storageBucket: "torsin-6084e.appspot.com",
//   messagingSenderId: "425305774130",
//   appId: "1:425305774130:web:a1b462f680f615e1c7842b",
//   measurementId: "G-7WNHDYT30W"
// };

// const firebaseApp = firebase.initializeApp(firebaseConfig);
// const messaging = getMessaging(firebaseApp)

// // Request permission to receive notifications
// messaging.requestPermission().then(() => {
//   console.log('Notification permission granted.');

//   // Get the token to identify the device
//   messaging.getToken().then((token) => {
//     console.log('Device token:', token);
//   }).catch((error) => {
//     console.log('Error getting device token:', error);
//   });
// }).catch((error) => {
//   console.log('Unable to get permission to notify.', error);
// });

// // Handle incoming messages while the app is in the foreground
// messaging.onMessage((payload) => {
//   console.log('Message received:', payload);
// });


export default function Home() {


  // useEffect(() => {
  //   const messaging = getMessaging();
  //   getToken(messaging, { vapidKey: 'BDYe0W7caIyp10JFWK0Wyq4BVI571xUiEwzZ01iwobVaBi80WQ9k720hAvaBogPJ-JqMGBlWte5d_hlicBT_0-8' }).then((currentToken) => {
  //     if (currentToken) {

  //       console.log(currentToken, "Fireabse token")
  //     } else {

  //       console.log('No registration token available. Request permission to generate one.');

  //     }
  //   }).catch((err) => {
  //     console.log('An error occurred while retrieving token. ', err);

  //   });

  // }, [])

  const router = useRouter();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const accessToken = localStorage.getItem("accessToken");
    process.browser && accessToken ? router.push("/dashboard") : setLoading(false);
  }, []);

  return (
    <div className={``}>
      {/* <button onClick={() => {
        Notification.requestPermission().then((data) => {
          new Notification(data)
        }).catch((error) => {
          console.log(error)
        })

      }}>
        Show
      </button> */}
      <Head>
        <title>Torsin Talent App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/torsinLogo.png" />
      </Head>

      <main className={``}>
        {
          loading ?
            <LazyLoader />
            :
            <MainPage />
        }
      </main>
    </div>
  )
}
