import React from 'react'
import Head from 'next/head';
import MainPage from "../src/components/common/MainPage";

export default function Home() {

    return (
        <div className={``}>
            <Head>
                <title>Torsin Talent App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/torsinLogo.png" />
            </Head>

            <main className={``}>
                <MainPage />
            </main>
        </div>
    )
}
